# Generated by Django 5.2.17 on 2026-09-15 22:55

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import portal.models
import portal.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
                ('fields', models.JSONField(blank=True, default=list, verbose_name='campos específicos')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_enabled', models.BooleanField(default=False, verbose_name='IA habilitada')),
                ('max_images', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='máximo de fotografías')),
                ('max_image_mb', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='MB por imagen')),
                ('max_video_mb', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='MB por video')),
                ('max_video_seconds', models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1800)], verbose_name='segundos por video')),
                ('ai_user_daily_limit', models.PositiveIntegerField(default=10, verbose_name='trabajos por usuario/día')),
                ('ai_global_daily_limit', models.PositiveIntegerField(default=100, verbose_name='trabajos globales/día')),
                ('ai_daily_token_limit', models.PositiveIntegerField(default=200000, verbose_name='límite global tokens/día')),
                ('ai_max_attempts', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='intentos IA')),
                ('legal_validated', models.BooleanField(default=False, verbose_name='documentos legales validados por IMC')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='correo comercial')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='teléfono comercial')),
                ('retention_days', models.PositiveIntegerField(default=365, validators=[django.core.validators.MinValueValidator(30)], verbose_name='días de conservación')),
            ],
            options={
                'verbose_name': 'configuración',
                'verbose_name_plural': 'configuración de la plataforma',
            },
        ),
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='clave')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('body', models.TextField(verbose_name='contenido en texto plano')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'contenido público',
                'verbose_name_plural': 'contenidos públicos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='celular')),
                ('contact_preference', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Llamada'), ('email', 'Correo')], default='email', max_length=12, verbose_name='contacto preferido')),
                ('advertiser_status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('suspended', 'Suspendido')], default='pending', max_length=16, verbose_name='permiso de anunciante')),
                ('email_verified', models.BooleanField(default=False, verbose_name='correo verificado')),
                ('company', models.CharField(blank=True, max_length=180, verbose_name='empresa')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='comunicaciones comerciales')),
                ('is_test', models.BooleanField(default=False, verbose_name='cuenta de prueba')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'permissions': [('manage_advertisers', 'Puede aprobar o suspender anunciantes'), ('operate_platform', 'Puede acceder al centro de operaciones')],
            },
            managers=[
                ('objects', portal.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('export', 'Exportar mis datos'), ('delete', 'Eliminar mi cuenta'), ('correction', 'Corregir mis datos')], max_length=12, verbose_name='solicitud')),
                ('detail', models.TextField(blank=True, verbose_name='detalle')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('completed', 'Completada')], default='pending', max_length=16, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud sobre datos personales',
                'verbose_name_plural': 'solicitudes sobre datos personales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='acción')),
                ('object_type', models.CharField(max_length=100, verbose_name='tipo')),
                ('object_id', models.CharField(max_length=100, verbose_name='identificador')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de auditoría',
                'verbose_name_plural': 'auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Mi maquinaria', max_length=180, verbose_name='título')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='datos')),
                ('provenance', models.JSONField(blank=True, default=dict, verbose_name='procedencia y revisión')),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='revisión')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviada a revisión'), ('in_review', 'En revisión'), ('changes_requested', 'Cambios solicitados'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], db_index=True, default='draft', max_length=24, verbose_name='estado')),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservada'), ('sold', 'Vendida'), ('withdrawn', 'Retirada')], default='available', max_length=16, verbose_name='disponibilidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.category', verbose_name='categoría')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'maquinaria',
                'verbose_name_plural': 'maquinarias',
                'ordering': ['-updated_at'],
                'permissions': [('review_submission', 'Puede resolver solicitudes'), ('publish_machine', 'Puede habilitar fichas y exportar publicaciones'), ('reassign_machine', 'Puede reasignar maquinaria')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='teléfono')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta')], default='normal', max_length=8, verbose_name='prioridad')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('contacted', 'Contactado'), ('qualified', 'Calificado'), ('closed', 'Cerrado')], default='new', max_length=12, verbose_name='estado')),
                ('next_action_at', models.DateTimeField(blank=True, null=True, verbose_name='próximo seguimiento')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notas internas')),
                ('is_test', models.BooleanField(default=False, verbose_name='prueba')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.machine')),
            ],
            options={
                'verbose_name': 'contacto comercial',
                'verbose_name_plural': 'contactos comerciales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('terms', 'Términos'), ('privacy', 'Privacidad'), ('ai', 'Análisis IA'), ('advertise', 'Difusión'), ('contact', 'Contacto público'), ('marketing', 'Marketing')], max_length=12, verbose_name='tipo')),
                ('version', models.CharField(default='2026-09', max_length=32)),
                ('granted', models.BooleanField(default=False, verbose_name='otorgado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='portal.machine')),
            ],
            options={
                'verbose_name': 'consentimiento',
                'verbose_name_plural': 'consentimientos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('original', models.FileField(max_length=500, storage=portal.storage.PrivateStorage(), upload_to=portal.models.private_asset_path, verbose_name='original privado')),
                ('preview', models.FileField(blank=True, max_length=500, null=True, storage=portal.storage.PrivateStorage(), upload_to=portal.models.private_asset_path, verbose_name='vista optimizada privada')),
                ('kind', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], max_length=8, verbose_name='tipo')),
                ('purpose', models.CharField(choices=[('general', 'Vista general'), ('plate', 'Placa'), ('detail', 'Detalle'), ('document', 'Documento privado')], default='general', max_length=12, verbose_name='contenido')),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False, verbose_name='portada')),
                ('public_authorized', models.BooleanField(default=False, verbose_name='difusión autorizada')),
                ('processing_status', models.CharField(choices=[('ready', 'Listo'), ('pending', 'Pendiente'), ('failed', 'Fallido')], default='pending', max_length=12, verbose_name='procesamiento')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='portal.machine')),
            ],
            options={
                'verbose_name': 'archivo privado',
                'verbose_name_plural': 'archivos privados',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=80, verbose_name='evento')),
                ('session_hash', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='origen')),
                ('campaign', models.CharField(blank=True, max_length=100, verbose_name='campaña')),
                ('device', models.CharField(blank=True, max_length=30, verbose_name='dispositivo')),
                ('is_test', models.BooleanField(default=False, verbose_name='prueba')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.machine')),
            ],
            options={
                'verbose_name': 'evento de analítica',
                'verbose_name_plural': 'analítica',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('asset_ids', models.JSONField(default=list)),
                ('mode', models.CharField(choices=[('analysis', 'Análisis'), ('description', 'Descripción')], default='analysis', max_length=12)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('running', 'En curso'), ('completed', 'Completado'), ('failed', 'Fallido')], db_index=True, default='queued', max_length=12, verbose_name='estado')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(default='2026-09-01', max_length=40)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('reserved_tokens', models.PositiveIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_jobs', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_jobs', to='portal.machine')),
            ],
            options={
                'verbose_name': 'trabajo de IA',
                'verbose_name_plural': 'trabajos de IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='número')),
                ('data', models.JSONField(default=dict, verbose_name='instantánea')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='portal.machine')),
            ],
            options={
                'verbose_name': 'versión de maquinaria',
                'verbose_name_plural': 'versiones de maquinaria',
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='approved_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_machines', to='portal.machineversion', verbose_name='versión aprobada'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='mensaje')),
                ('internal', models.BooleanField(default=False, verbose_name='nota interna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='portal.machine')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=180, verbose_name='asunto')),
                ('body', models.TextField(verbose_name='contenido')),
                ('channel', models.CharField(choices=[('in_app', 'En plataforma'), ('email', 'Correo')], default='in_app', max_length=8, verbose_name='canal')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('failed', 'Fallida')], default='pending', max_length=8, verbose_name='estado')),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('share', 'Ficha compartible'), ('main', 'Portal principal')], default='share', max_length=8, verbose_name='destino')),
                ('status', models.CharField(choices=[('unpublished', 'Sin publicar'), ('approved', 'Aprobada'), ('exported', 'Exportada'), ('published', 'Publicada'), ('failed', 'Error'), ('disabled', 'Deshabilitada')], default='unpublished', max_length=16, verbose_name='estado')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=False, verbose_name='habilitada')),
                ('external_id', models.CharField(blank=True, max_length=200, verbose_name='identificador externo')),
                ('external_url', models.URLField(blank=True, verbose_name='enlace externo')),
                ('last_error', models.TextField(blank=True, verbose_name='último error')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='portal.machine')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.machineversion')),
            ],
            options={
                'verbose_name': 'publicación',
                'verbose_name_plural': 'publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviada a revisión'), ('in_review', 'En revisión'), ('changes_requested', 'Cambios solicitados'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], db_index=True, default='submitted', max_length=24, verbose_name='estado')),
                ('message', models.TextField(blank=True, verbose_name='observaciones')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='portal.machine')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.machineversion')),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_case_insensitive'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status', 'created_at'], name='portal_anal_status_573ccc_idx'),
        ),
        migrations.AddConstraint(
            model_name='machineversion',
            constraint=models.UniqueConstraint(fields=('machine', 'number'), name='unique_machine_version'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['owner', 'status'], name='portal_mach_owner_i_04ef85_idx'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(fields=('machine', 'destination'), name='unique_publication_destination'),
        ),
    ]
