# Generated by Django 5.2.17 on 2026-09-15 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='símbolo')),
                ('dimension', models.CharField(blank=True, max_length=60, verbose_name='magnitud')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'unidad de medida',
                'verbose_name_plural': 'unidades de medida',
                'ordering': ['dimension', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='modelo')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_models', to='portal.brand', verbose_name='marca')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'modelo de equipo',
                'verbose_name_plural': 'modelos de equipo',
                'ordering': ['brand__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'name'), name='unique_brand_equipment_model')],
            },
        ),
    ]
