# Generated by Django 5.2.17 on 2026-09-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_brand_unit_equipmentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(choices=[('submission', 'Solicitud recibida'), ('review_in_review', 'Revisión iniciada'), ('review_changes_requested', 'Correcciones solicitadas'), ('review_approved', 'Ficha aprobada'), ('review_rejected', 'Ficha rechazada'), ('review_cancelled', 'Solicitud cancelada'), ('advertiser', 'Permiso de anunciante'), ('reminder', 'Recordatorio'), ('reassignment', 'Reasignación')], unique=True, verbose_name='clave')),
                ('subject', models.CharField(max_length=180, verbose_name='asunto')),
                ('body', models.TextField(help_text='Variables admitidas: $folio, $status, $reason, $title, $name y $portal_url. Usa $$ para un signo de dólar literal.', verbose_name='contenido en texto plano')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'plantilla de notificación',
                'verbose_name_plural': 'plantillas de notificaciones',
                'ordering': ['key'],
            },
        ),
        migrations.AlterModelOptions(
            name='analyticsevent',
            options={'ordering': ['-created_at'], 'permissions': [('export_analytics', 'Puede exportar eventos de analítica')], 'verbose_name': 'evento de analítica', 'verbose_name_plural': 'analítica'},
        ),
    ]
