# Generated by Django 5.2.17 on 2026-09-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_notificationtemplate_alter_analyticsevent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='registration_open',
            field=models.BooleanField(default=False, help_text='Sólo abre registros cuando los documentos legales también estén validados.', verbose_name='registro público abierto'),
        ),
    ]
