# Generated by Django 5.2.17 on 2026-09-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_platformsettings_registration_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='analytics_context',
            field=models.JSONField(blank=True, default=dict, verbose_name='contexto de analítica opcional'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='actor_type',
            field=models.CharField(choices=[('anonymous', 'Anónimo'), ('registered', 'Registrado sin identificar'), ('staff', 'Equipo interno'), ('test', 'Prueba')], db_index=True, default='anonymous', max_length=12, verbose_name='tipo de visitante'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='page',
            field=models.CharField(blank=True, max_length=40, verbose_name='área de navegación'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='analytics_enabled',
            field=models.BooleanField(default=False, verbose_name='analítica de adquisición habilitada'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='analytics_require_consent',
            field=models.BooleanField(default=True, help_text='Si se desactiva este requisito, sólo se recogen contadores agregados sin cookies ni identificadores hasta una aceptación expresa. Un rechazo siempre detiene la captura.', verbose_name='analítica sólo con consentimiento'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='kind',
            field=models.CharField(choices=[('terms', 'Términos'), ('privacy', 'Privacidad'), ('ai', 'Análisis IA'), ('advertise', 'Difusión'), ('contact', 'Contacto público'), ('marketing', 'Marketing'), ('analytics', 'Analítica opcional')], max_length=12, verbose_name='tipo'),
        ),
    ]
