# Generated by Django 5.2.17 on 2026-09-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_open_user_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='application_result',
            field=models.JSONField(blank=True, default=dict, verbose_name='resultado del completado automático'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='application_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='base para completar el borrador'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='auto_apply',
            field=models.BooleanField(default=False, verbose_name='completar huecos del borrador automáticamente'),
        ),
    ]
