# Generated by Django 5.2.17 on 2026-09-16 03:53

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_automatic_draft_completion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-updated_at'], 'permissions': [('review_submission', 'Puede resolver solicitudes'), ('publish_machine', 'Puede habilitar fichas y exportar publicaciones'), ('reassign_machine', 'Puede reasignar maquinaria')], 'verbose_name': 'maquinaria', 'verbose_name_plural': 'maquinarias'},
        ),
        migrations.AlterModelManagers(
            name='machine',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='en papelera desde'),
        ),
    ]
