# Generated by Django 5.2.17 on 2026-09-16 06:59

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_draft_trash'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('login', 'Inicio de sesión'), ('session', 'Sesión activa'), ('mfa_verified', 'Segundo factor verificado')], max_length=20, verbose_name='evento')),
                ('connection_ip', models.GenericIPAddressField(blank=True, help_text='Dirección observada por el servidor; puede corresponder al proxy del alojamiento.', null=True, verbose_name='IP de conexión')),
                ('forwarded_ip', models.GenericIPAddressField(blank=True, help_text='Dato no verificado de X-Forwarded-For. No se usa para autorizar ni identifica una ubicación física.', null=True, verbose_name='IP declarada por la cabecera de red')),
                ('device', models.CharField(choices=[('desktop', 'Computadora'), ('mobile', 'Celular'), ('tablet', 'Tableta'), ('unknown', 'Sin identificar')], default='unknown', max_length=10, verbose_name='tipo de dispositivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('expires_at', models.DateTimeField(db_index=True, default=portal.models.account_access_expiry, verbose_name='eliminar después de')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_history', to=settings.AUTH_USER_MODEL, verbose_name='cuenta')),
            ],
            options={
                'verbose_name': 'acceso de cuenta',
                'verbose_name_plural': 'accesos e IP de cuentas',
                'ordering': ['-created_at'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='account_access_user_date')],
            },
        ),
    ]
