# Generated by Django 5.2.17 on 2026-09-18 19:52

import django.core.validators
import django.db.models.deletion
import re
from decimal import Decimal, InvalidOperation
from django.conf import settings
from django.db import migrations, models


def backfill_version_search_fields(apps, schema_editor):
    """Project immutable legacy snapshots only; do not modify Machine records.

    This deliberately keeps a small frozen parser in the migration. Importing
    the evolving runtime projection here could make old snapshots migrate to a
    different answer after a later deployment.
    """

    MachineVersion = apps.get_model("portal", "MachineVersion")
    Category = apps.get_model("portal", "Category")
    database = schema_editor.connection.alias
    fields = ("category", "brand", "model", "variant", "undercarriage", "hours", "year",
              "estimated_year_from", "estimated_year_to", "price", "currency", "weight_kg",
              "digging_depth_m", "location_country", "location_region", "location_city",
              "preservation_condition")
    decimal_re = re.compile(r"^[+-]?\d+(?:[.,]\d+)?$")
    measure_re = re.compile(r"^\s*([+-]?(?:\d+(?:[.,]\d+)?))\s*([A-Za-z0-9³^]+)\s*$", re.I)

    def decimal(value):
        if isinstance(value, bool) or value is None or value == "":
            return None
        if isinstance(value, Decimal):
            return value
        if isinstance(value, int):
            return Decimal(value)
        text = str(value).strip().replace(" ", "")
        if not decimal_re.fullmatch(text) or (text.count(",") + text.count(".") == 1 and len(re.split("[,.]", text)[1]) == 3):
            return None
        try:
            return Decimal(text.replace(",", "."))
        except InvalidOperation:
            return None

    def bounded(value, maximum):
        return value if value is not None and 0 <= value < maximum else None

    def measure(value, units, maximum):
        raw = re.sub(r"(?<=\d)\s+(?=\d)", "", str(value or "").replace("\u00a0", " "))
        match = measure_re.fullmatch(raw)
        if not match:
            return None
        amount, factor = decimal(match.group(1)), units.get(match.group(2).casefold().replace("³", "3"))
        return bounded(amount * factor if amount is not None and factor is not None else None, maximum)

    def text(value, limit):
        return " ".join(value.split())[:limit] if isinstance(value, str) and value.strip() else ""

    def year(value):
        value = decimal(value)
        return int(value) if value is not None and value == value.to_integral_value() and 1800 <= value <= 2200 else None

    for version in MachineVersion.objects.using(database).iterator(chunk_size=200):
        data = version.data if isinstance(version.data, dict) else {}
        source = data.get("data", {}) if isinstance(data.get("data"), dict) else {}
        category_id = data.get("category")
        category = Category.objects.using(database).filter(pk=category_id).first() if isinstance(category_id, int) else None
        price = bounded(decimal(source.get("price")), Decimal("1e14"))
        currency = str(source.get("currency") or "").strip().upper()
        price_meta = data.get("provenance", {}).get("price", {}) if isinstance(data.get("provenance"), dict) else {}
        if price is None or price < 0 or not re.fullmatch(r"[A-Z]{3}", currency) or (isinstance(price_meta, dict) and price_meta.get("source") == "valuation" and price_meta.get("review") != "confirmed"):
            price, currency = None, ""
        start, end = year(source.get("estimated_year_from")), year(source.get("estimated_year_to"))
        if start is not None and end is not None and start > end:
            start = end = None
        preservation = {"excelente": "excellent", "buena": "good", "bueno": "good", "aceptable": "acceptable", "deficiente": "poor"}.get(str(source.get("preservation_condition") or "").strip().casefold(), source.get("preservation_condition") if source.get("preservation_condition") in {"excellent", "good", "acceptable", "poor"} else "")
        values = {
            "category": category, "brand": text(source.get("brand"), 100), "model": text(source.get("model"), 100),
            "variant": text(source.get("variant"), 180), "undercarriage": source.get("undercarriage") if source.get("undercarriage") in {"crawler", "wheeled", "special"} else "",
            "hours": bounded(decimal(source.get("hours")), Decimal("1e12")),
            "year": year(source.get("year")), "estimated_year_from": start, "estimated_year_to": end,
            "price": price, "currency": currency,
            "weight_kg": measure(source.get("weight"), {"kg": Decimal("1"), "t": Decimal("1000"), "ton": Decimal("1000"), "tons": Decimal("1000"), "lb": Decimal("0.45359237"), "lbs": Decimal("0.45359237")}, Decimal("1e11")),
            "digging_depth_m": measure(source.get("digging_depth"), {"m": Decimal("1"), "cm": Decimal("0.01"), "mm": Decimal("0.001"), "ft": Decimal("0.3048"), "in": Decimal("0.0254")}, Decimal("1e9")),
            "location_country": text(source.get("location_country"), 80), "location_region": text(source.get("location_region"), 120),
            "location_city": text(source.get("location_city"), 120), "preservation_condition": preservation,
        }
        MachineVersion.objects.using(database).filter(pk=version.pk).update(**{name: values[name] for name in fields})


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_notification_read_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineversion',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='marca indexada'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_versions', to='portal.category', verbose_name='categoría indexada'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='currency',
            field=models.CharField(blank=True, max_length=3, verbose_name='moneda indexada'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='digging_depth_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='profundidad m indexada'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='estimated_year_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2200)], verbose_name='año estimado desde'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='estimated_year_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2200)], verbose_name='año estimado hasta'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='horas indexadas'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='location_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='ciudad indexada'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='location_country',
            field=models.CharField(blank=True, max_length=80, verbose_name='país indexado'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='location_region',
            field=models.CharField(blank=True, max_length=120, verbose_name='estado o provincia indexado'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='modelo indexado'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='preservation_condition',
            field=models.CharField(blank=True, max_length=16, verbose_name='conservación indexada'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio indexado'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='undercarriage',
            field=models.CharField(blank=True, max_length=32, verbose_name='rodamiento indexado'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='variant',
            field=models.CharField(blank=True, max_length=180, verbose_name='variante indexada'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='peso kg indexado'),
        ),
        migrations.AddField(
            model_name='machineversion',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2200)], verbose_name='año exacto indexado'),
        ),
        migrations.CreateModel(
            name='TechnicalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='marca')),
                ('model', models.CharField(max_length=100, verbose_name='modelo')),
                ('variant', models.CharField(blank=True, max_length=180, verbose_name='variante')),
                ('generation', models.CharField(blank=True, max_length=120, verbose_name='generación')),
                ('market', models.CharField(blank=True, max_length=80, verbose_name='mercado')),
                ('period_from', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2200)], verbose_name='periodo desde')),
                ('period_to', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2200)], verbose_name='periodo hasta')),
                ('specs', models.JSONField(blank=True, default=dict, verbose_name='especificaciones documentadas')),
                ('provenance', models.JSONField(blank=True, default=dict, verbose_name='procedencia')),
                ('source', models.URLField(max_length=1000, verbose_name='fuente primaria')),
                ('source_title', models.CharField(max_length=300, verbose_name='título de fuente')),
                ('source_version', models.CharField(blank=True, max_length=100, verbose_name='versión de fuente')),
                ('retrieved_at', models.DateField(verbose_name='consultada el')),
                ('review', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_index=True, default='pending', max_length=12, verbose_name='revisión')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisada el')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_references', to='portal.category', verbose_name='categoría')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_technical_references', to=settings.AUTH_USER_MODEL, verbose_name='revisada por')),
            ],
            options={
                'verbose_name': 'referencia técnica',
                'verbose_name_plural': 'referencias técnicas',
                'ordering': ['category__name', 'brand', 'model', 'variant', 'market'],
                'indexes': [models.Index(fields=['category', 'brand', 'model', 'variant', 'market', 'active'], name='portal_tech_categor_92b79f_idx')],
            },
        ),
        migrations.RunPython(backfill_version_search_fields, migrations.RunPython.noop),
    ]
