# Generated by Django 5.2.17 on 2026-09-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_technical_knowledge_and_version_search'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='machineversion',
            index=models.Index(fields=['category', 'brand', 'model', 'variant', 'undercarriage'], name='version_identity_search'),
        ),
        migrations.AddIndex(
            model_name='machineversion',
            index=models.Index(fields=['category', 'year', 'estimated_year_from', 'estimated_year_to'], name='version_year_search'),
        ),
        migrations.AddIndex(
            model_name='machineversion',
            index=models.Index(fields=['category', 'currency', 'price'], name='version_price_search'),
        ),
        migrations.AddIndex(
            model_name='machineversion',
            index=models.Index(fields=['category', 'location_country', 'location_region', 'location_city'], name='version_location_search'),
        ),
        migrations.AddIndex(
            model_name='machineversion',
            index=models.Index(fields=['category', 'weight_kg', 'digging_depth_m', 'hours'], name='version_specs_search'),
        ),
    ]
