# Generated by Django 5.2.17 on 2026-09-22 17:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_technical_reference_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField(max_length=1000, unique=True, verbose_name='URL de fuente')),
                ('source_title', models.CharField(max_length=300, verbose_name='título de fuente')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('MXN', 'MXN'), ('EUR', 'EUR')], max_length=3, verbose_name='moneda')),
                ('market', models.CharField(max_length=2, verbose_name='mercado')),
                ('price_type', models.CharField(choices=[('asking', 'Precio anunciado'), ('sold', 'Precio de venta')], default='asking', max_length=10, verbose_name='tipo de precio')),
                ('condition', models.CharField(choices=[('new', 'Nueva'), ('used', 'Usada'), ('refurbished', 'Reacondicionada'), ('for_repair', 'Para reparación'), ('unknown', 'Sin confirmar')], default='unknown', max_length=16, verbose_name='condición')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2200)], verbose_name='año')),
                ('hours', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='horas')),
                ('retrieved_at', models.DateField(verbose_name='consultada el')),
                ('evidence', models.TextField(verbose_name='evidencia')),
                ('configurations', models.JSONField(blank=True, default=dict, verbose_name='configuración')),
                ('unit_key', models.CharField(blank=True, max_length=128, verbose_name='clave de unidad')),
                ('review', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_index=True, default='pending', max_length=12, verbose_name='revisión')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='activa')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisada el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_references', to='portal.equipmentmodel', verbose_name='modelo del catálogo')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_market_references', to=settings.AUTH_USER_MODEL, verbose_name='revisada por')),
            ],
            options={
                'verbose_name': 'referencia de mercado',
                'verbose_name_plural': 'referencias de mercado',
                'ordering': ['equipment_model__brand__name', 'equipment_model__name', '-retrieved_at'],
                'indexes': [models.Index(fields=['equipment_model', 'market', 'currency', 'price_type', 'condition', 'active'], name='portal_mark_equipme_646bb3_idx')],
            },
        ),
    ]
