# Generated by Django 5.2.17 on 2026-09-22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_market_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketreference',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16,
                                      validators=[django.core.validators.MinValueValidator(Decimal('0.01'))],
                                      verbose_name='precio'),
        ),
        migrations.AddConstraint(
            model_name='marketreference',
            constraint=models.CheckConstraint(
                condition=models.Q(('active', False), ('review', 'approved'), _connector='OR'),
                name='market_active_requires_approval',
            ),
        ),
        migrations.AddConstraint(
            model_name='marketreference',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='market_price_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='technicalreference',
            constraint=models.CheckConstraint(
                condition=models.Q(('active', False), ('review', 'approved'), _connector='OR'),
                name='technical_active_requires_approval',
            ),
        ),
        migrations.AddConstraint(
            model_name='technicalreference',
            constraint=models.CheckConstraint(
                condition=models.Q(('period_from__isnull', True), ('period_to__isnull', True),
                                   ('period_from__lte', models.F('period_to')), _connector='OR'),
                name='technical_period_is_ordered',
            ),
        ),
    ]
