# Generated by Django 5.2.17 on 2026-09-23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0015_reference_integrity"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="external_reference",
            field=models.CharField(blank=True, max_length=200, verbose_name="referencia visible externa"),
        ),
        migrations.AddField(
            model_name="publication",
            name="integration_state",
            field=models.CharField(choices=[("pending", "Pendiente"), ("acknowledged", "Acusada")], default="pending", max_length=16, verbose_name="estado de integración"),
        ),
        migrations.AddField(
            model_name="publication",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="acuse registrado"),
        ),
        migrations.AddField(
            model_name="publication",
            name="acknowledged_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name="acknowledged_publications", to=settings.AUTH_USER_MODEL,
                                    verbose_name="acuse registrado por"),
        ),
        migrations.CreateModel(
            name="IntegrationDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_machine_id", models.UUIDField(editable=False, verbose_name="identificador estable de maquinaria")),
                ("payload", models.JSONField(default=dict, verbose_name="carga preparada")),
                ("payload_sha256", models.CharField(max_length=64, verbose_name="huella de carga")),
                ("state", models.CharField(choices=[("prepared", "Preparada"), ("acknowledged", "Acusada")], db_index=True, default="prepared", max_length=16, verbose_name="estado")),
                ("receipt", models.JSONField(blank=True, default=dict, verbose_name="acuse remoto declarado")),
                ("evidence", models.TextField(blank=True, verbose_name="evidencia independiente")),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                       related_name="acknowledged_deliveries", to=settings.AUTH_USER_MODEL)),
                ("publication", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deliveries", to="portal.publication")),
                ("version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="integration_deliveries", to="portal.machineversion")),
            ],
            options={"verbose_name": "entrega de integración", "verbose_name_plural": "entregas de integración", "ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="publication",
            name="current_delivery",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name="+", to="portal.integrationdelivery", verbose_name="entrega activa"),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.UniqueConstraint(condition=models.Q(("destination", "main"), models.Q(("external_id", ""), _negated=True), _connector="AND"), fields=("destination", "external_id"), name="unique_main_external_id"),
        ),
        migrations.AddConstraint(
            model_name="integrationdelivery",
            constraint=models.UniqueConstraint(fields=("publication", "version", "payload_sha256"), name="unique_delivery_payload_version"),
        ),
    ]
