# Generated by Django 5.2.17 on 2026-09-25 06:12

import django.db.models.deletion
import portal.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_main_integration_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(db_index=True, default=False, verbose_name='principal técnico temporal'),
        ),
        migrations.CreateModel(
            name='GuestDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True, default=portal.models.guest_draft_expiry)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_guest_drafts', to=settings.AUTH_USER_MODEL)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guest_draft', to='portal.machine')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guest_draft', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'borrador temporal',
                'verbose_name_plural': 'borradores temporales',
            },
        ),
    ]
