# Generated by Django 5.2.17 on 2026-10-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0023_correct_electric_platform_energy"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestTrial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("browser_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("draft", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name="trial", to="portal.guestdraft")),
            ],
            options={
                "verbose_name": "uso gratuito de visitante",
                "verbose_name_plural": "usos gratuitos de visitantes",
            },
        ),
    ]
