const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM,VirtualConsole}=require('jsdom');
const source=fs.readFileSync(path.join(__dirname,'../static/portal/notification-center.js'),'utf8');
const markup=`<input id="draft" value="Corrección sin guardar"><a id="notification-bell" href="/panel/notificaciones/" data-viewer="1" data-summary-url="/panel/notificaciones/resumen/" data-unread-count="2" data-latest-id="7" aria-label="Notificaciones: 2 sin leer"><span id="notification-badge">2</span></a><section id="notification-pending-banner"><strong id="notification-pending-title">Tienes 2 avisos sin leer</strong><p id="notification-pending-subject">Aviso previo</p><a id="notification-pending-link" href="/panel/notificaciones/7/">Ver observación</a><button data-dismiss-notification="banner"></button></section><div id="notification-arrival" hidden><div role="status" aria-live="polite"><p id="notification-arrival-subject"></p></div><a id="notification-arrival-link"></a><button data-dismiss-notification="arrival"></button></div><article data-notification-item="7" class="is-unread"><span class="notification-read-state">Sin leer</span><form data-notification-read action="/panel/notificaciones/7/leer/"><input name="csrfmiddlewaretoken" value="synthetic-csrf"><button type="submit">Marcar</button><p class="notification-read-status" hidden></p></form></article><form data-notification-read data-mark-all action="/panel/notificaciones/leer-todas/"><input name="csrfmiddlewaretoken" value="synthetic-csrf"><button type="submit">Todas</button><p class="notification-read-status" hidden></p></form>`;
const result=(count=2,id=7,extra={})=>({viewer_id:'1',unread_count:count,latest:count?{id,subject:'Observación '+id,body:'Detalle privado',url:'/panel/notificaciones/'+id+'/'}:null,...extra});
const response=(status,data,extra={})=>({status,ok:status>=200&&status<300,redirected:false,headers:{get:()=> 'application/json'},json:async()=>data,...extra});
const settle=async()=>{for(let i=0;i<15;i++)await Promise.resolve();};
let checks=0;const pass=name=>{checks++;console.log('PASS '+name);};
function setup(fetcher,options={}){
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!e.message.includes('navigation'))errors.push(e.message);});
 const dom=new JSDOM(options.anonymous?'<input id="draft">':markup.replace('data-latest-id="7"',`data-latest-id="${options.latestId||7}"`),{url:'https://test.invalid/panel/maquinarias/test/',runScripts:'outside-only',virtualConsole:vc});
 const w=dom.window,d=w.document,timers=new Map(),calls=[];let now=0,tid=0,hidden=!!options.hidden;
 Object.defineProperty(d,'hidden',{get:()=>hidden});
 w.setTimeout=(fn,delay=0)=>{const id=++tid;timers.set(id,{fn,at:now+delay});return id;};w.clearTimeout=id=>timers.delete(id);
 w.fetch=async(...args)=>{calls.push(args);return fetcher(...args);};
 Object.defineProperty(w,'localStorage',{get(){throw Error('No persistent account storage');}});
 Object.defineProperty(w,'sessionStorage',{get(){throw Error('No persistent account storage');}});
 d.querySelector('#draft').focus();w.eval(source);
 return {w,d,calls,timers,async tick(ms){const end=now+ms;for(let i=0;i<100;i++){await settle();const next=[...timers.entries()].filter(([,t])=>t.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!next){now=end;await settle();return;}now=next[1].at;timers.delete(next[0]);next[1].fn();}throw Error('Timer runaway');},async visibility(value){hidden=value;d.dispatchEvent(new w.Event('visibilitychange'));await settle();},submit(all=false){d.querySelector(all?'[data-mark-all]':'[data-notification-item] form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));},close(){assert.deepEqual(errors,[]);dom.window.close();}};
}
(async()=>{
 const anon=setup(()=>{throw Error('Anonymous request');},{anonymous:true});await anon.tick(90000);assert.equal(anon.calls.length,0);assert.equal(anon.timers.size,0);anon.close();pass('anonymous pages do not poll or allocate notification state');
 const idle=setup(async()=>response(200,result()));await idle.tick(29999);assert.equal(idle.calls.length,0);await idle.tick(1);assert.equal(idle.calls.length,1);assert.equal(idle.calls[0][1].credentials,'same-origin');assert.equal(idle.calls[0][1].cache,'no-store');assert.equal(idle.d.querySelector('#notification-arrival').hidden,true);assert.equal(idle.d.activeElement.id,'draft');assert.equal(idle.d.querySelector('#draft').value,'Corrección sin guardar');idle.close();pass('SSR state stays immediate; polling waits thirty seconds and preserves dirty form focus');
 const unsafe=result(103,8);unsafe.latest.subject='<img src=x onerror=alert(1)>';unsafe.latest.url='javascript:alert(1)';
 const arrival=setup(async()=>response(200,unsafe));await arrival.tick(30000);assert.equal(arrival.d.querySelector('#notification-badge').textContent,'99+');assert.equal(arrival.d.querySelector('#notification-arrival').hidden,false);assert.equal(arrival.d.querySelector('#notification-arrival-subject').textContent,unsafe.latest.subject);assert.equal(arrival.d.querySelectorAll('#notification-arrival img,script').length,0);assert.equal(arrival.d.querySelector('#notification-arrival-link').pathname,'/panel/notificaciones/');assert.equal(arrival.d.activeElement.id,'draft');arrival.d.querySelector('[data-dismiss-notification=arrival]').click();await arrival.tick(30000);assert.equal(arrival.d.querySelector('#notification-arrival').hidden,true);arrival.close();pass('new notice is announced once without focus theft; 99+ badge and textContent block injection');
 const paused=setup(async()=>response(200,result(3,8)),{hidden:true});await paused.tick(120000);assert.equal(paused.calls.length,0);await paused.visibility(false);await paused.tick(0);assert.equal(paused.calls.length,1);await paused.visibility(true);await paused.tick(120000);assert.equal(paused.calls.length,1);assert.equal(paused.d.querySelector('#notification-arrival').hidden,true);paused.close();pass('hidden tab polling pauses and resumes with one visible refresh');
 for(const kind of ['unauthorized','redirect','html','viewer']){const c=setup(async()=>kind==='unauthorized'?response(401,{}):kind==='redirect'?response(200,{}, {redirected:true}):kind==='html'?response(200,{}, {headers:{get:()=> 'text/html'}}):response(200,result(2,8,{viewer_id:'2'})));await c.tick(30000);await c.visibility(true);await c.visibility(false);await c.tick(300000);assert.equal(c.calls.length,1,kind);assert.equal(c.d.querySelector('#notification-badge').hidden,true);assert.equal(c.d.querySelector('#notification-pending-banner').hidden,true);assert.equal(c.d.querySelector('#notification-arrival-subject').textContent,'');c.close();}pass('expired session, redirects, HTML login and changed account stop polling and clear alerts');
 let attempts=0;const retry=setup(async()=>++attempts<3?response(500,{}):response(200,result()));await retry.tick(30000);assert.equal(attempts,1);await retry.tick(59999);assert.equal(attempts,1);await retry.tick(1);assert.equal(attempts,2);await retry.tick(120000);assert.equal(attempts,3);assert.equal(retry.d.querySelector('#notification-arrival').hidden,true);retry.close();pass('transient failures back off silently without notification spam');
 const mark=setup(async(url,options)=>{assert.equal(options.method,'POST');assert.equal(options.headers['X-CSRFToken'],'synthetic-csrf');assert.equal(options.body.get('csrfmiddlewaretoken'),'synthetic-csrf');return response(200,result(0));});assert.equal(mark.calls.length,0);mark.submit();mark.submit();await settle();assert.equal(mark.calls.length,1);assert.equal(mark.d.querySelector('#notification-badge').hidden,true);assert.equal(mark.d.querySelector('.notification-read-state').textContent,'Leída');assert.equal(mark.d.querySelector('[data-notification-item] form').hidden,true);mark.close();pass('explicit mark-read sends CSRF once and updates badge plus read state without navigation');
 const all=setup(async()=>response(200,result(0)));all.submit(true);await settle();assert.equal(all.d.querySelector('[data-mark-all]').hidden,true);assert.equal(all.d.querySelectorAll('.is-unread').length,0);assert.equal(all.d.querySelector('#notification-arrival').hidden,true);all.close();pass('mark-all updates visible cards and clears the pending banner');
 let fail=true;const failure=setup(async()=>fail?response(500,{}):response(200,result(0)));failure.submit();await settle();assert.equal(failure.d.querySelector('[data-notification-item] form').hidden,false);assert.equal(failure.d.querySelector('[data-notification-item] button').disabled,false);assert.match(failure.d.querySelector('.notification-read-status').textContent,/reintentar/);assert.equal(failure.d.querySelector('#notification-badge').textContent,'2');fail=false;failure.submit();await settle();assert.equal(failure.d.querySelector('#notification-badge').hidden,true);failure.close();pass('failed mark-read retains unread state and allows an explicit retry');
 let release;const race=setup(async(url,options)=>options.method==='POST'?response(200,result(0)):await new Promise(resolve=>release=()=>resolve(response(200,result(2,8)))));await race.tick(30000);assert.equal(race.calls.length,1);race.submit();await settle();assert.equal(race.d.querySelector('#notification-badge').hidden,true);release();await settle();assert.equal(race.d.querySelector('#notification-badge').hidden,true);assert.equal(race.d.querySelector('#notification-arrival').hidden,true);race.close();pass('summary started before mark-read cannot restore stale counts or replay an alert');
 const dismiss=setup(async()=>response(200,result(2,7)));dismiss.d.querySelector('[data-dismiss-notification=banner]').click();await dismiss.tick(30000);assert.equal(dismiss.d.querySelector('#notification-pending-banner').hidden,true);dismiss.w.fetch=async()=>response(200,result(3,9));await dismiss.tick(30000);assert.equal(dismiss.d.querySelector('#notification-pending-banner').hidden,false);dismiss.close();pass('dismissing a banner is tab-local; a later notice remains discoverable');
 let current=9;const older=setup(async()=>response(200,result(1,current)),{latestId:10});await older.tick(30000);assert.equal(older.d.querySelector('#notification-arrival').hidden,true);assert.equal(older.d.querySelector('#notification-badge').textContent,'1');current=11;await older.tick(30000);assert.equal(older.d.querySelector('#notification-arrival').hidden,false);assert.equal(older.d.querySelector('#notification-arrival-subject').textContent,'Observación 11');older.close();pass('reading newest notice in another tab does not announce an older unread item as new');
 let hangs=0;const timeout=setup(async(url,options)=>{hangs++;if(hangs>1)return response(200,result());return new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>{const error=new Error('Aborted');error.name='AbortError';reject(error);}));});await timeout.tick(30000);assert.equal(hangs,1);await timeout.tick(15000);assert.equal(timeout.calls[0][1].signal.aborted,true);await timeout.tick(59999);assert.equal(hangs,1);await timeout.tick(1);assert.equal(hangs,2);timeout.close();pass('hung polling is aborted after fifteen seconds and retried with backoff');
 console.log(`Notification center DOM: ${checks} groups PASS`);
})().catch(error=>{console.error(error);process.exitCode=1;});
